name: spotify_clone
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  marquee: ^2.2.3


  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true


  assets:
    - images/
    - images/artists/
    - images/podcasts/

  fonts:
    - family: AM
      fonts:
        - asset: fonts/Avenir Medium.ttf

    - family: AB
      fonts:
        - asset: fonts/Avenir Next LT Pro Bold.otf
